model:
  device: "cpu"
  model_name: "pidnet_l"
  weight_path: "pidnet_pretrained_model/PIDNet_L_Cityscapes_test.pt"
  # weight_path: "models/road_segmentation_best.pth"  # The original Resnet101 model is too slow and not accurate enough, so we switched to PIDNet_L 

input:
  image_path: "inference_datasets/solid_line/up_hile/images/000201.png"
  image_batch_path: "inference_datasets/solid_line/up_hile/images"
  image_batch_size: 305
  resize_size:
    - 512
    - 1024

road_segmentation:
  # threshold: 0.5  # The original Resnet101 model is too slow and not accurate enough, so we switched to PIDNet_L 
  # mask_erosion_kernel: 3  # Erode mask inward by this many pixels to eliminate edge artifacts

lane_segmentation:
  min_slope: 0.3
  min_segment_length: 45  # Discard ELSED segments shorter than this (pixels)
  # roi: 0.2
  lane_band_tolerance: 10  # Max x_at_bottom deviation (pixels) from innermost segment to still be considered the same lane marking

lane_fitting:
  extra_points_per_segment: 10
  num_bands: 3  # Number of horizontal bands for piecewise linear fitting
  num_samples: 20  # Number of y-values to sample for lane width computation
  # ransac_residual_threshold: 5.0  # Max pixel distance from fitted line to be considered an inlier

pitch_estimation:
  f_x: 512  # Focal length calculated from camera intrinsics and resize dimensions
  f_y: 455
  w_real: 3.5  # Get from carla

visualization:
  alpha: 0.4
  save_path: "outputs/result.png"

csv_io:
  input_dir: "outputs/metadata_gt.csv"
  output_dir: "outputs/metadata_gt.csv"