dataset:
  train:
    image_dir: "libs/dataset/cityscape/leftImg8bit/train"
    label_dir: "libs/dataset/cityscape/gtFine/train"
  val:
    image_dir: "libs/dataset/cityscape/leftImg8bit/val"
    label_dir: "libs/dataset/cityscape/gtFine/val"

training:
  batch_size: 4
  epochs: 10
  learning_rate: 0.001
  shuffle: true
  aux_loss_weight: 0.4

model:
  device: "cuda"

checkpoint:
  save_best_path: "models/road_segmentation_best.pth"